### ISSUE TITLE
issue in make compile

### ISSUE THREAD

**Issue by gsscoder** [clojang/lfecljapp#14]
I post the latest part of output:

```
/Users/giacomo/clones/lfecljapp/deps/lfe/src/lfe_codegen.erl:957: Warning: variable 'St' shadowed in 'fun'
/Users/giacomo/clones/lfecljapp/deps/lfe/src/lfe_codegen.erl:962: Warning: variable 'St' shadowed in 'fun'
Compiled src/lfe_codegen.erl
Compiling c_src/lfeexec.c
c_src/lfeexec.c:67:9: warning: incompatible pointer types assigning to 'char **' from 'char *' [-Wincompatible-pointer-types]
  Eargv = emalloc(sizeof(*argv) * (argc + 16));
        ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
==> lfecljapp (compile)
cp: ./ebin/lfecljapp.app: No such file or directory
make: *** [erlang] Error 1
```

Probably a dependency err? Do you want me output something about my system?

Thanks in adavance... :)

**Comment by oubiwann** [comment]
The 2013 build code has been replaced with 2017 build code (e.g., latest lein, latest rebar3, etc.).

It's getting a big makeover now, using jiface/clojang -- still a work in progress (no supervision tree updates yet), but both LFE and Clojure compile for me.

If you're still interested, give it a try and let me know how it goes. (Instructions in the README are up to date).

**Comment by oubiwann** [comment]
I've confirmed this as fixed on my end with the new code. Will close now, but if the issue still lingers in outlying circumstances, we can re-open.
